[package]
name = "container_pull"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12"
tokio = { version = "1.*", features = ["macros", "rt-multi-thread", "test-util", "sync", "parking_lot", "rt"] }
containerd-client = "0.8.0"
tokio-stream = "0.1.17"
uuid = { version = "1.13.1", features = ["v4"] }
prost-types = "0.13.4"